### ISSUE TITLE
Tests missing in sdist tarballs on pypi.org

### ISSUE THREAD

**Issue by dvzrv** [sde1000/python-xkbcommon#10]
Hi! When trying to package version 0.3 of this project for Arch Linux I tried to run tests for it.
Unfortunately the tests are not contained in the sdist tarball and as there are no release tarballs on github either, I am unable to run tests.

It would be really awesome if you could add them (additionally to tagging the respective versions #9 ).

**Comment by sde1000** [comment]
Thanks for pointing this out. Can you check the changes in pull request #12 and let me know if they fix the issue?
