### ISSUE TITLE
error at installation

### ISSUE THREAD

**Issue by jpx40** [sde1000/python-xkbcommon#15]
Hello, 
the installation of python-xkbcommon rebately fails i am using fedora 36. I attached an file with the error message.

[error.txt](https://github.com/sde1000/python-xkbcommon/files/9905355/error.txt)

**Comment by sde1000** [comment]
You need to have the libxkbcommon headers and library files installed. I'm not a Fedora user so I can't easily test, but this should be package `libxkbcommon-devel`

**Comment by JonasPeitz** [comment]
> You need to have the libxkbcommon headers and library files installed. I'm not a Fedora user so I can't easily test, but this should be package `libxkbcommon-devel`

**Comment by jpx40** [comment]
thank you, it works  for me now
