### ISSUE TITLE
Update to v1.0.0 (funcs xkb_utf32_to_keysym, xkb_keymap_key_get_mods_for_level)

### ISSUE THREAD

**Issue by ldrahnik** [sde1000/python-xkbcommon#19]
Hello there!

do you think that would be possible add funcs `xkb_utf32_to_keysym` and `xkb_keymap_key_get_mods_for_level` which have been added into [libxkbcommon ](https://github.com/xkbcommon/libxkbcommon/tree/master) by [changelog](https://github.com/xkbcommon/libxkbcommon/blob/master/xkbcommon.map) in next v1.0.0? (I could offer to create a pull request eventually)

[Link](https://github.com/asus-linux-drivers/asus-numberpad-driver/pull/175) to a related project that would use both func in the same way as it uses [how-to-type](https://github.com/xkbcommon/libxkbcommon/blob/master/tools/how-to-type.c) tool from libxkbcommon repository.

**Comment by sde1000** [comment]
Adding `xkb_keymap_key_get_mods_for_level` sounds reasonable, I'll have a look at that.

`xkb_utf32_to_keysym` sounds less useful; python doesn't deal in utf32 very often, I'm not sure how I would expose that in the python bindings. I could include it in the ffi module I suppose.

**Comment by sde1000** [comment]
Can you let me know if #20 does what you need?

**Comment by ldrahnik** [comment]
Exactly, what we need. The added code I did not test. Should I?

**Comment by sde1000** [comment]
If you can check that it does what you expect, that would be good. I had a quick look while I was writing the test for it, and it appears to return plausible sets of modifiers for keys, but I don't use that call myself so I don't know if it's right.

**Comment by ldrahnik** [comment]
Could you guide me how to initiate the project and run the test on local machine (Ubuntu 22.04 aswell) ? Because `$ pytest` in root gives me `ModuleNotFoundError: No module named 'xkbcommob._ffi'`

```
$ cd python-xkbcommon
# init?
$ pytest
```

**Comment by sde1000** [comment]
These days see https://setuptools.pypa.io/en/latest/userguide/development_mode.html

```
$ cd python-xkbcommon
$ python3 -m venv .venv
$ source .venv/bin/activate
$ pip install --editable .
$ pytest
```

**Comment by ldrahnik** [comment]
AFAIK it can be merged. The while True: cycle sounds better than allocating entire space at start `typedef uint32_t 	xkb_mod_mask_t`  ([typedefs](https://xkbcommon.org/doc/current/xkbcommon_8h.html#a41b3ee62ae73ec041b68165bf97869e8)) with consideration the most used count of modifiers will not be far away from currently used 21.

About your idea of a helper: might be useful to have an equivalent for this function `string_to_keycode` (written in c already [here](https://github.com/roscale/zenith/blob/f38f553ab428ae12fee7a63704de36f46d7ee1e9/src/util/embedder/keyboard_helpers.cpp#L4)) which returns:

```
*return_value = KeyCombination{
     .modifiers = mask,
     keycode = key,
};
return;
````

**Comment by sde1000** [comment]
Ok, I'll make a release 1.0 which includes this, and upload it to pypi.

**Comment by ldrahnik** [comment]
Thank you!
