### ISSUE TITLE
Building wheel fails

### ISSUE THREAD

**Issue by ldrahnik** [sde1000/python-xkbcommon#26]
Hi,

I am not sure what happened but the building wheel fails:

```
build/temp.linux-x86_64-cpython-310/xkbcommon._ffi.c:1017:12: error: ‘XKB_CONTEXT_NO_SECURE_GETENV’ undeclared (first use in this function); did you mean ‘_cffi_const_XKB_CONTEXT_NO_SECURE_GETENV’?
1017 | int n = (XKB_CONTEXT_NO_SECURE_GETENV) <= 0;
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
| _cffi_const_XKB_CONTEXT_NO_SECURE_GETENV
build/temp.linux-x86_64-cpython-310/xkbcommon._ffi.c:1017:12: note: each undeclared identifier is reported only once for each function it appears in
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
```

reported [here](https://github.com/asus-linux-drivers/asus-numberpad-driver/issues/186). 

I have not replicated the same problem in my environment, yet.

**Comment by sde1000** [comment]
The system you are building on has a version of libxkbcommon that is lower than 1.5.

The project should depend on `xkbcommon<1.1` instead of just `xkbcommon`.
