### ISSUE TITLE
Bindings for libxkbregistry

### ISSUE THREAD

**Issue by hickford** [sde1000/python-xkbcommon#7]
Thank you for the bindings, I've found them useful. Do you plan to include similar bindings for libxkbregistry?

https://xkbcommon.org/doc/current/group__registry.html

> The libxkbregistry API to query for available rules, models, layouts, variants and options (RMLVO). libxkbregistry is a separate library to libxkbcommon. This library is the replacement for clients currently parsing evdev.xml directly. 

https://github.com/xkbcommon/libxkbcommon/blob/master/PACKAGING

> libxkbregistry is a sublibrary of libxkbcommon and cannot be built without building libxbkcommon. The files produced are otherwise independent.

**Comment by sde1000** [comment]
I wasn't aware of libxkbregistry before. I see it is quite new: released with libxkbcommon 1.0.0 on 5th September 2020.

I've had a quick read of its API and I don't see any reason why it can't be supported. It could either be supported in a new python library (eg. "python-xkbregistry") or as a separate module inside python-xkbcommon.

**Comment by hickford** [comment]
Indeed it's new. For example https://packages.debian.org/sid/main/libxkbregistry-dev is in Debian testing but not yet in stable. 

Since libxkbregistry is a separate package in distributions such as Debian and Fedora, perhaps the Python bindings should be a separate package too. Otherwise it would prevent installing this Python package on systems without libxkbregistry

**Comment by sde1000** [comment]
Bindings for libxkbregistry now exist at https://github.com/sde1000/python-xkbregistry — comments welcome there!

**Comment by hickford** [comment]
Awesome work, thank you
