### ISSUE TITLE
Compose and dead keys support

### ISSUE THREAD

**Issue by hickford** [sde1000/python-xkbcommon#8]
The compose and dead key functions are missing bindings https://xkbcommon.org/doc/current/group__compose.html

**Comment by sde1000** [comment]
An initial implementation of this is in 1b823f726b6b3c9a2a4fdb15abf9726226458dfd — testing and comments welcome before I make a release containing it.

Only took three years :-)

**Comment by mbey-mw** [comment]
Works for me - but I didn't have to wait for that :grin:

**Comment by sde1000** [comment]
I've released version 1.0.1 that includes this. I've also added support for the compose table iterator introduced in libxkbcommon-1.6 — not released yet, comments welcome.
